# Generated by Django 5.2.5 on 2025-08-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(default='Main Course', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gourmet Manager', max_length=200)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('email', models.EmailField(default='info@gourmetmanager.com', max_length=254)),
                ('address', models.TextField(default='123 Food Street, Culinary City')),
                ('welcome_message', models.TextField(default='Welcome to our restaurant! We serve love on every plate.')),
            ],
        ),
    ]
