# Generated by Django 5.2.5 on 2025-08-24 15:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='welcome_message',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.CharField(default='St. Louis', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='owner_name',
            field=models.CharField(default='Unknown Owner', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(default='Unnamed Restaurant', max_length=255),
        ),
    ]
